### ISSUE TITLE
Error: "platform_browser_1.__platform_browser_private__.getDOM(...).getCookie is not a function.."

### ISSUE THREAD

**Issue by danmo** [simpulton/ngrx-rest-app#12]
Did a clean clone, npm install, typings install and npm start. Getting the following error in the browser: "platform_browser_1.__platform_browser_private__.getDOM(...).getCookie is not a function" Cancel and Save don't seem to work.

**Comment by jdgarvey** [comment]
Found the problem, we had not locked all of the different Angular packages to the same version. Should be fixed now, try a clean install again.
